In [77]:
from pandas import DataFrame, read_excel
from bokeh import charts
#from bokeh.charts import Bar, output_file, show
#from bokeh.charts.attributes import cat, color
#from bokeh.charts.operations import blend

In [78]:
df = read_excel("Growth of MathCS Data.xlsx")
#df = df.set_index('Quarter')
df

,Quarter,Math-Computer Science (MATH),Computer Science (CSE),Computer Engineering (CSE),Bioinformatics (CSE),Computer Engineering (ECE),Computation (COGS),Human-Computer Interaction (COGS)
0,Fall '11,14,896,242,50,74,16,53
1,Winter '12,20,937,226,51,62,22,72
2,Spring '12,25,912,220,48,51,25,82
3,Fall '12,33,1238,345,67,94,23,93
4,Winter '13,29,1292,321,66,78,23,107
5,Spring '13,32,1309,304,67,73,23,121
6,Fall '13,70,1460,370,112,122,17,115
7,Winter '14,84,1455,329,122,117,21,126
8,Spring '14,91,1433,296,124,151,18,122
9,Fall '14,193,1704,359,111,257,24,109
10,Winter '15,246,1703,330,96,270,26,145
11,Spring '15,293,1679,298,81,268,40,168
12,Fall '15,602,1885,317,69,320,47,170
13,Winter '16,747,1802,301,66,313,53,209

In [87]:
bar = Bar(df, 
          values= blend('Math-Computer Science (MATH)', 'Computer Science (CSE)', 'Computer Engineering (CSE)',
                       'Bioinformatics (CSE)', 'Computer Engineering (ECE)', 'Computation (COGS)', 'Human-Computer Interation (COGS)'
                       , name='major', labels_name='majors'),
          #label= cat( columns='Quarter', sort=False),
          #stack= cat(columns='majors', sort=False),
          legend='top_left', title="Growth of Math-Computer Science among Computer Science-related majors.")

In [88]:
output_file("MathCS_StackedBar.html")

show(bar)